### ISSUE TITLE
Add "why did you say that" to module system

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy#103]
Robert Miles [15 Feb 2021 at 02:58](https://trello.com/c/8aHF1F9m/4-add-why-did-you-say-that-to-module-system#comment-6029e34d3264bd6ffa992ccc)
@chrisrimmer12 I mean 2. It's actually already implemented, but it only works for some of the features. Whenever you set a response, you also set a "why" variable with an explanation of the response. Asking why just gives back the latest 'why' string.
The next level of complexity up is to keep track of this longer term, so you can reply to a message with "why did you say that". That's more hassle than it's worth right now though, I think

[Reply](https://trello.com/c/8aHF1F9m/4-add-why-did-you-say-that-to-module-system#)
Chris Rimmer [10 Feb 2021 at 02:37](https://trello.com/c/8aHF1F9m/4-add-why-did-you-say-that-to-module-system#comment-60234708cc78795565d84883)
Is this:

1- To qualify a message as a postfix
"Stampy tell me a joke"
"
Two guys stole a calendar. They got six months each.
This was sent from my jokes module because it matched on "tell me a joke
"

2- To handle follow-up messages:
"Stampy tell me a joke"
"'Tell Me A Joke' is the name of a 2011 single by Nicolas Clays and Max Walder"
"Why did you say that?"
"Because the message you sent registered a match in my media library"

1 is easier but obviously gets visually noisy.
2 would require that Stampy remember data about its last message which while not hard, is a tad more complex.

**Comment by tayler6000** [comment]
@jmccuen I'm going to assign this to you since I believe you were already working on this.  If not, or if you've abandoned it, feel free to unassign it from yourself.
