### ISSUE TITLE
"Ok, I'll post when..." messages use replies and are purged when fulfilled

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy#105]
Damaged
Messages such as: Ok, I'll post this when it has more than 30 stamp points should probably be replies to the comment they're from, and if the user deletes their comment, Stampy could probably just delete the replies.
If you have stampy set up with manage_messages you could use await TextChannel.purge ( [API Reference](https://discordpy.readthedocs.io/en/v1.6.0/api.html#discord.TextChannel.purge) ) and use a check function that checks if the comments belong to stampy, are replies, and then that they're replies to the message that was deleted.

robertskmiles
That's a good idea. That functionality predates replies, which is why they're not already done that way

Yevgeniy
"Ok, posting ..." replies to the answer

**Comment by MatthewBaggins** [comment]
Isn't this actually outdated? @plexish

**Comment by plexish** [comment]
Yes, this is about a system we're not focusing on currently.
