### ISSUE TITLE
Stamp threshold for automatically getting @member

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy#112]

**Comment by plexish** [comment]
When he gives the role to someone, he should @ them and say the factoid "$newmember"

**Comment by tayler6000** [comment]
@plexish Is this still a high priority in your opinion?  Also, for sake of the discussion, my stamps are currently 281.76 so I think 100 stamps may be a good number.  But we should probably wait to see where stamps land after #213 is merged.

**Comment by plexish** [comment]
Not high priority, no. Might be useful one day, but not urgent.
