### ISSUE TITLE
Stampy API access for ui.stampy.ai

### ISSUE THREAD

**Issue by jmccuen** [StampyAI/stampy#148]
@plexish suggested we may need to add or edit questions directly from the UI. Since we currently already have an API wrapper for Semantic wiki that is aware of our question / meta tag format, I think it makes sense to do this via the Stampy flask API. I have an initial example of this in the [flask_api branch](https://github.com/robertskmiles/stampy/tree/flask_api), but have some questions around how public this API be will  -- i.e. do we need to authenticate requests to it, how do we track who on the UI is opening the question, etc.

Also, need to detail what all features we want -- just add questions? Edit or remove questions? etc

**Comment by plexish** [comment]
We're going with React secrets for now, closing until further notice.
