### ISSUE TITLE
Serve the Stamps csv file via flask so the wiki can read it

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy#186]
TODO: Ask plex/rob in the meantime

**Comment by robertskmiles** [comment]
Currently the code writes the file to `/var/www/html/stamps-export.csv`, which used to be served by apache when the wiki and bot were on the same server. Probably that should be changed to `~/stampy.local` and the flask api should read out the file. Or we could just keep the csv string in memory.

**Comment by plexish** [comment]
Needs rethinking with respect to coda.
