### ISSUE TITLE
FAQ Module

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy#188]
@AugustusCeasar knows

**Comment by robertskmiles** [comment]
Some overlap with https://github.com/StampyAI/stampy/pull/198 which does basic FAQ semantic search using the new SS API

**Comment by MatthewBaggins** [comment]
Isn't this outdated? @plexish

**Comment by plexish** [comment]
considerably outdated, might be worth picking up some of the ideas sometime, but let's close for now. Will see how the chat + FAQ system settles, then come back to this.
