### ISSUE TITLE
Stamps system not updating

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy#204]
Giving people stamps no longer causes them to gain stamps in [our eigenkarma system](https://aisafety.info?state=6465_). It would be really great to have this fixed ASAP.

**Comment by bmillwood** [comment]
I'm looking into this (though I've never looked at this part of the code before.)

**Comment by bmillwood** [comment]
My findings so far are that my local stampy has no trouble updating and reporting stamp counts.

**Comment by bmillwood** [comment]
We figured out this was because Stampy no longer had an accurate name for the server, so guild lookup was failing.

**Comment by bmillwood** [comment]
- Related: https://github.com/StampyAI/stampy/pull/208

**Comment by plexish** [comment]
> We figured out this was because Stampy no longer had an accurate name for the server, so guild lookup was failing.

ah, that's on me, thanks for tracking it down!
