### ISSUE TITLE
Make all the stampy reacts also give stamps

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy#218]

**Comment by tayler6000** [comment]
You're talking about the Stampy logo reacts right?  If so, I thought those intentionally didn't give stamps, so that you could give a stamp without giving a true stamp?

**Comment by plexish** [comment]
Not intentional, we just added the stampy reacts after the stamps system was built. Rob said he wanted all the stampy stamps to be counted today in a call

**Comment by tayler6000** [comment]
Copy
