### ISSUE TITLE
Discord ID's are hardcoded

### ISSUE THREAD

**Issue by ProducerMatt** [StampyAI/stampy#248]
In my limited tests the most immediate issues are the admin user and role ID's. In my branch I'm going to switch them to environment variables. Any objections?

Would anyone mind if I start work on *completely* removing the preset ID's and making them external?

**Comment by ProducerMatt** [comment]
Working on it in this draft PR: https://github.com/StampyAI/stampy/pull/254

**Comment by tayler6000** [comment]
I think that would be mostly good but we would need to update the .env on Stampy's server before merge.
