### ISSUE TITLE
question_setter module firing at unwanted times

### ISSUE THREAD

**Issue by ProducerMatt** [StampyAI/stampy#297]
Example:

> User: I think mine’s done, i’ve gone on to checking the stampychat code for embedding the huggingface dataset. The PR requires a review, and also says ‘this branch has conflicts that must be resolved’, but it said that earlier and I merged it with main, and I’m guessing I don’t have to do that continually we can just do it before or as the PR gets accepted?
> Edit: btw despite saying ‘requiring a review’ I think it’s pretty much been reviewed already so maybe I meant it required an approval but perhaps there’s some bug I haven’t figured out who knows)
> 
> Stampy: You're not a reviewer, @user -_-

**Comment by ProducerMatt** [comment]
@MatthewBaggins are you "Mateusz"?

**Comment by MatthewBaggins** [comment]
Hopefully will make a PR fixing this today
