### ISSUE TITLE
Tags are sometimes not loaded

### ISSUE THREAD

**Issue by Aprillion** [StampyAI/stampy#324]
I haven't investigated in detail yet, but sometimes tags don't load (see top of screenshot), with no errors in browser console => will need to send some debug info from server side rendering 🤔 

![image](https://github.com/StampyAI/stampy/assets/1087670/1ff7e4df-8b77-49a5-90a6-3a93fb9a60ac)

**Comment by ProducerMatt** [comment]
@Aprillion i think you meant to post to `stampy-ui`

**Comment by Aprillion** [comment]
dammit, yes, thanks 🙇
