### ISSUE TITLE
Add bar with link to survey

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy#328]
**Acceptance criteria**

- Add a bar for the survey CTA across the top of every page of the website
  - Make it match the Figma visually for both desktop and mobile
  - If user either clicks X or takes the survey, remove the bar (ideally it never shows up again for that user but not sure how to do this without cookies)
  - Survey should open in a new tab
- Some notes on visuals
  - In the button component there is the default, then there is a class for large. I have now in Figma added small to the component ( [component in Figma](https://www.figma.com/design/qqfeYAh6Z7QdyJXsQjIUfh/.info%3A-Redesign-1.0?node-id=1034-1713&m=dev&t=CihGV5XCxJvfyRPZ-1) ), so add this class or whatever to the component in react. Height is 40px left right padding is 12px, type is same as default.

**links**

Design: https://www.figma.com/design/SXOSWCqlbt4VvXaMHTtCDb/.info%3A-etc.-(Copy)?node-id=8210-917&m=dev&t=VaZ1kjiO3E5SseZ3-1
Survey: https://79385avet9x.typeform.com/to/cyfXg3je

**Comment by ProducerMatt** [comment]
Wrong repo, sorry 😄

**Comment by mruwnik** [comment]
@melissasamworth @ProducerMatt so should this be reopened or something?

**Comment by ProducerMatt** [comment]
@mruwnik @melissasamworth  should reopen in the actual repo it applies to, there's no way to move it
