### ISSUE TITLE
Make the recalculate stamp karma function write to a publicly readable .csv for wiki use

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy#55]
https://www.mediawiki.org/wiki/Extension:External_Data##get_web_data_-_CSV,_GFF,_JSON,_XML,_HTML can grab it for wiki integration if we have it in a text file

**Comment by plexish** [comment]
this is written, but not public, see #186

**Comment by tayler6000** [comment]
@plexish do you want to close this since you've also closed #186 or do you want to leave it open as the new tracker for the idea?

**Comment by plexish** [comment]
hmm, this would be nice to keep actually, for letting coda read it.
